require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

abstract_target 'App' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MyApp' do
    #Production-specific pods

    target 'MyAppTests' do
      inherit! :complete
      # Pods for testing
    end
  end

  target 'MyAppDevelopment' do
    #Development-specific pods
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyApp-tvOS' do
  # Pods for MyApp-tvOS

  target 'MyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
